
FROM composer:2.5 AS composer

FROM php:7.3 AS builder

COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN apt-get update && apt-get install -y unzip

WORKDIR /app/
COPY . /app

RUN cd web && composer install --ignore-platform-reqs

RUN ./web/vendor/bin/phpunit tests
