
FROM composer:2.5 as composer

FROM php:7.2 as builder

COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN apt update && apt install -y unzip

WORKDIR /app/
COPY . /app

RUN cd web && composer install --ignore-platform-reqs

RUN ./web/vendor/bin/phpunit tests
